<HomeScreenView>
    MDScreen:
        MDNavigationLayout:
            ScreenManager:
                MDScreen:
                    MDToolbar:
                        title: app.title
                        elevation: 10
                        pos_hint: {"top": 1}
                        left_action_items:
                            [['menu', lambda x: nav_drawer.set_state("open")]]

            MDNavigationDrawer:
                id: nav_drawer
                ContentNavigationDrawer: